# Generated by Django 5.0.1 on 2024-02-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekermodule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='tenth_marks',
            field=models.CharField(max_length=20),
        ),
    ]
