# Generated by Django 5.0.1 on 2024-03-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employermodule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='review',
            field=models.TextField(default='review'),
            preserve_default=False,
        ),
    ]
